### ISSUE TITLE
New install config

### ISSUE THREAD

**Issue by spoonwzd** [BJReplay/PowerwallService#11]
The following lines must be removed from the config:

```
      <Setting Name="PWPeakConsumptionWeekend" Type="System.String" Scope="Application">
      	<!--Consumption expected during peak hours on the weekend-->
        <Value>17500</Value>
      </Setting>
```

Because the service won't start if they are...

```
Service cannot be started. System.Configuration.ConfigurationErrorsException: The configuration section cannot contain a CDATA or text element. (C:\PowerwallService\PowerwallService.exe.Config line 284)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, ...
```

**Comment by BJReplay** [comment]
Build 1.4.3.1 Release Notes

** IMPORTANT - BAD SAMPLE CONFIG ENTRIES **

A number of config entries were listed incorrectly as shown immediately below - with a Type Attribute and Scope Attribute and a Profile Attribute
These are incorrect.

    <Setting Name="DebugLogging" Type="System.Boolean" Scope="Application">
      <Value Profile="(Default)">False</Value>
    </Setting>    


The correct form for these is as shown below.
For information about each setting, refer to the original release notes below.

    <Setting Name="DebugLogging" serializeAs="String">
      <Value>False</Value>
    </Setting>            
    <setting name="PWControlEnabled" serializeAs="String">
      <value>True</value>
    </setting>
    <Setting Name="PWOvernightStandby" serializeAs="String">
      <Value>False</Value>
    </Setting>
    <Setting Name="PWWeekendStandbyTarget" serializeAs="String">
      <Value>5</Value>
    </Setting>
    <Setting Name="PWWeekendStandbyOnTarget" serializeAs="String">
      <Value>False</Value>
    </Setting>
