### ISSUE TITLE
1.0.1 & 1.4.2.1 - PWPeakConsumptionWeekend setting causing service to not start

### ISSUE THREAD

**Issue by AnthonyBe** [BJReplay/PowerwallService#16]
This setting was causing my service to not start.
Firstly, it is case-sensitive and so didn't like the capital 'S' in Setting, 'N' in Name, etc.
It seemed to keep throwing an error on 'Type' irrespective of what case I used so I just removed that setting block entirely as I'm only currently using it for logging.
```
      <Setting Name="PWPeakConsumptionWeekend" Type="System.String" Scope="Application">
      	<!--Consumption expected during peak hours on the weekend-->
        <Value>17500</Value>
      </Setting>
```

Event log error:

```
Log Name:      Application
Source:        PowerwallService
Date:          16/04/2018 8:47:14 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ANTNEWPC
Description:
Service cannot be started. System.Configuration.ConfigurationErrorsException: Unrecognized attribute 'Type'. Note that attribute names are case-sensitive. (D:\Applications\PowerwallService\PowerwallService.exe.Config line 281)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean request...

```

**Comment by BJReplay** [comment]
Build 1.4.3.1 Release Notes

** IMPORTANT - BAD SAMPLE CONFIG ENTRIES **

A number of config entries were listed incorrectly as shown immediately below - with a Type Attribute and Scope Attribute and a Profile Attribute
These are incorrect.

    <Setting Name="DebugLogging" Type="System.Boolean" Scope="Application">
      <Value Profile="(Default)">False</Value>
    </Setting>    


The correct form for these is as shown below.
For information about each setting, refer to the original release notes below.

    <Setting Name="DebugLogging" serializeAs="String">
      <Value>False</Value>
    </Setting>            
    <setting name="PWControlEnabled" serializeAs="String">
      <value>True</value>
    </setting>
    <Setting Name="PWOvernightStandby" serializeAs="String">
      <Value>False</Value>
    </Setting>
    <Setting Name="PWWeekendStandbyTarget" serializeAs="String">
      <Value>5</Value>
    </Setting>
    <Setting Name="PWWeekendStandbyOnTarget" serializeAs="String">
      <Value>False</Value>
    </Setting>
