### ISSUE TITLE
Violation of Integer Constraint

### ISSUE THREAD

**Issue by gibbo9000** [BJReplay/PowerwallService#30]
Some unique combination of values in Config or Powerwall seems to be loading a non-integer into backup_reserve_percent.  Not critical as can be worked around, but thought worth noting.  Config file is attached.  Error is:

Log Name:      Application
Source:        PowerwallService
Date:          19/09/2018 5:47:49 PM
Event ID:      0

Description:
Input string '14.5' is not a valid integer. Path 'backup_reserve_percent', line 1, position 55.

   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at PowerwallService.PowerwallService.GetPWSecureAPIResult[JSONType](String API, Boolean ForceReLogin)

[PowerwallService.exe.zip](https://github.com/BJReplay/PowerwallService/files/2397018/PowerwallService.exe.zip)

**Comment by BJReplay** [comment]
Thanks, I'll look into this.  I've had a GitHub branch management failure, and have had to manually re-apply fixes in my working branch back into master, and think I've missed changing the percentage from integer to decimal in the master branch.

**Comment by BJReplay** [comment]
@gibbo9000 - see https://github.com/BJReplay/PowerwallService/blob/master/PowerwallServiceBeta1.7.2.0.zip for a build that should fix this.
